CREATE TABLE IF NOT EXISTS "age_group" (
	"AGE_GROUP_CODE"	INTEGER,
	"UPPER_AGE"	INTEGER,
	"LOWER_AGE"	INTEGER,
	PRIMARY KEY (AGE_GROUP_CODE)
);

CREATE TABLE IF NOT EXISTS "sales_territory" (
    "SALES_TERRITORY_CODE"	INTEGER,
    "TERRITORY_NAME_EN"	TEXT,
	PRIMARY KEY (SALES_TERRITORY_CODE)
);

CREATE TABLE IF NOT EXISTS "retailer_segment" (
    "SEGMENT_CODE"	INTEGER,
    "LANGUAGE"	TEXT,
    "SEGMENT_NAME"	TEXT,
    "SEGMENT_DESCRIPTION"	TEXT,
	PRIMARY KEY (SEGMENT_CODE)
);

CREATE TABLE IF NOT EXISTS "order_method" (
	"ORDER_METHOD_CODE"	INTEGER,
	"ORDER_METHOD_EN"	TEXT,
	PRIMARY KEY (ORDER_METHOD_CODE)
);

CREATE TABLE IF NOT EXISTS "course" (
	"COURSE_CODE"	INTEGER,
	"COURSE_DESCRIPTION"	TEXT,
	PRIMARY KEY (COURSE_CODE)
);

CREATE TABLE IF NOT EXISTS "return_reason" (
	"RETURN_REASON_CODE"	INTEGER,
	"RETURN_DESCRIPTION_EN"	TEXT,
	PRIMARY KEY (RETURN_REASON_CODE)
);

CREATE TABLE IF NOT EXISTS "satisfaction_type" (
	"SATISFACTION_TYPE_CODE"	INTEGER,
	"SATISFACTION_TYPE_DESCRIPTION"	TEXT,
	PRIMARY KEY (SATISFACTION_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS "product_line" (
	"PRODUCT_LINE_CODE"	INTEGER,
	"PRODUCT_LINE_EN"	TEXT,
	PRIMARY KEY (PRODUCT_LINE_CODE)
);

CREATE TABLE IF NOT EXISTS "retailer_type" (
    "RETAILER_TYPE_CODE"	INTEGER,
    "RETAILER_TYPE_EN"	TEXT,
	PRIMARY KEY (RETAILER_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS "country" (
    "COUNTRY_CODE"	INTEGER,
    "COUNTRY_EN"	TEXT,
    "LANGUAGE"      TEXT,
    "FLAG_IMAGE"	TEXT,
    "CURRENCY_NAME" TEXT,
    "SALES_TERRITORY_CODE"	INTEGER,
	PRIMARY KEY (COUNTRY_CODE),
	FOREIGN KEY (SALES_TERRITORY_CODE) REFERENCES sales_territory(SALES_TERRITORY_CODE)
);

CREATE TABLE IF NOT EXISTS "sales_branch" (
	"SALES_BRANCH_CODE"	INTEGER,
	"ADDRESS1"	TEXT,
	"ADDRESS2"	TEXT,
	"CITY"	TEXT,
	"REGION"	TEXT,
	"POSTAL_ZONE"	TEXT,
	"COUNTRY_CODE"	INTEGER,
	PRIMARY KEY (SALES_BRANCH_CODE),
	FOREIGN KEY (COUNTRY_CODE) REFERENCES country(COUNTRY_CODE)
);

CREATE TABLE IF NOT EXISTS "product_type" (
	"PRODUCT_TYPE_CODE"	INTEGER,
	"PRODUCT_LINE_CODE"	INTEGER,
	"PRODUCT_TYPE_EN"	TEXT,
	PRIMARY KEY (PRODUCT_TYPE_CODE),
	FOREIGN KEY (PRODUCT_LINE_CODE) REFERENCES product_line(PRODUCT_LINE_CODE)
);

CREATE TABLE IF NOT EXISTS "product" (
	"PRODUCT_NUMBER"	INTEGER,
	"INTRODUCTION_DATE"	TEXT,
	"PRODUCT_TYPE_CODE"	INTEGER,
	"PRODUCTION_COST"	REAL,
	"MARGIN"	REAL,
	"PRODUCT_IMAGE"	TEXT,
	"LANGUAGE"	TEXT,
	"PRODUCT_NAME"	TEXT,
	"DESCRIPTION"	TEXT,
	PRIMARY KEY (PRODUCT_NUMBER),
	FOREIGN KEY (PRODUCT_TYPE_CODE) REFERENCES product_type(PRODUCT_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS "retailer_headquarters" (
    "RETAILER_CODEMR"	INTEGER,
    "RETAILER_NAME"	TEXT,
    "ADDRESS1"	TEXT,
    "ADDRESS2"	TEXT,
    "CITY"	TEXT,
    "REGION"	TEXT,
    "POSTAL_ZONE"	TEXT,
    "COUNTRY_CODE"	INTEGER,
    "PHONE"	TEXT,
    "FAX"	TEXT,
    "SEGMENT_CODE"	INTEGER,
	PRIMARY KEY (RETAILER_CODEMR),
	FOREIGN KEY (COUNTRY_CODE) REFERENCES country(COUNTRY_CODE),
	FOREIGN KEY (SEGMENT_CODE) REFERENCES retailer_segment(SEGMENT_CODE)
);

CREATE TABLE IF NOT EXISTS "sales_staff" (
	"SALES_STAFF_CODE"	INTEGER,
	"FIRST_NAME"	TEXT,
	"LAST_NAME"	TEXT,
	"POSITION_EN"	TEXT,
	"WORK_PHONE"	TEXT,
	"EXTENSION"	INTEGER,
	"FAX"	TEXT,
	"EMAIL"	TEXT,
	"DATE_HIRED"	TEXT,
	"SALES_BRANCH_CODE"	INTEGER,
	"MANAGER_CODE"	INTEGER,
	PRIMARY KEY (SALES_STAFF_CODE),
	FOREIGN KEY (SALES_BRANCH_CODE) REFERENCES sales_branch(SALES_BRANCH_CODE),
	FOREIGN KEY (MANAGER_CODE) REFERENCES sales_staff(SALES_STAFF_CODE)
);

CREATE TABLE IF NOT EXISTS "retailer" (
    "RETAILER_CODE"	INTEGER,
    "RETAILER_CODEMR"	INTEGER,
    "COMPANY_NAME"	TEXT,
    "RETAILER_TYPE_CODE"	INTEGER,
	PRIMARY KEY (RETAILER_CODE),
	FOREIGN KEY (RETAILER_CODEMR) REFERENCES retailer_headquarters(RETAILER_CODEMR)
);

CREATE TABLE IF NOT EXISTS "training" (
	"YEAR"	INTEGER,
	"SALES_STAFF_CODE"	INTEGER,
	"COURSE_CODE"	INTEGER,
	PRIMARY KEY (SALES_STAFF_CODE, COURSE_CODE),
	FOREIGN KEY (SALES_STAFF_CODE) REFERENCES sales_staff(SALES_STAFF_CODE),
	FOREIGN KEY (COURSE_CODE) REFERENCES course(COURSE_CODE)

);

CREATE TABLE IF NOT EXISTS "sales_demographic" (
    "DEMOGRAPHIC_CODE"	INTEGER,
    "RETAILER_CODEMR"	INTEGER,
    "AGE_GROUP_CODE"	INTEGER,
    "SALES_PERCENT"	INTEGER,
	PRIMARY KEY (DEMOGRAPHIC_CODE),
	FOREIGN KEY (RETAILER_CODEMR) REFERENCES retailer_headquarters(RETAILER_CODEMR),
	FOREIGN KEY (AGE_GROUP_CODE) REFERENCES age_group(AGE_GROUP_CODE)
);

CREATE TABLE IF NOT EXISTS "retailer_site" (
    "RETAILER_SITE_CODE"	INTEGER,
    "RETAILER_CODE"	INTEGER,
    "ADDRESS1"	TEXT,
    "ADDRESS2"	TEXT,
    "CITY"	TEXT,
    "REGION"	TEXT,
    "POSTAL_ZONE"	TEXT,
    "COUNTRY_CODE"	INTEGER,
    "ACTIVE_INDICATOR"	INTEGER,
	PRIMARY KEY (RETAILER_SITE_CODE),
	FOREIGN KEY (RETAILER_CODE) REFERENCES retailer(RETAILER_CODE),
	FOREIGN KEY (COUNTRY_CODE) REFERENCES country(COUNTRY_CODE)
);

CREATE TABLE IF NOT EXISTS "retailer_contact" (
    "RETAILER_CONTACT_CODE"	INTEGER,
    "RETAILER_SITE_CODE"	INTEGER,
    "FIRST_NAME"	TEXT,
    "LAST_NAME"	TEXT,
    "JOB_POSITION_EN"	TEXT,
    "EXTENSION"	INTEGER,
    "FAX"	TEXT,
    "E_MAIL"	TEXT,
    "GENDER"	TEXT,
	PRIMARY KEY (RETAILER_CONTACT_CODE),
	FOREIGN KEY (RETAILER_SITE_CODE) REFERENCES retailer_site(RETAILER_SITE_CODE)
);

CREATE TABLE IF NOT EXISTS IF NOT EXISTS "satisfaction" (
	"YEAR"	INTEGER,
	"SALES_STAFF_CODE"	INTEGER,
	"SATISFACTION_TYPE_CODE"	INTEGER,
	PRIMARY KEY (SALES_STAFF_CODE, SATISFACTION_TYPE_CODE),
	FOREIGN KEY (SALES_STAFF_CODE) REFERENCES sales_staff(SALES_STAFF_CODE),
	FOREIGN KEY (SATISFACTION_TYPE_CODE) REFERENCES satisfaction_type(SATISFACTION_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS "order_header" (
	"ORDER_NUMBER"	INTEGER,
	"RETAILER_NAME"	TEXT,
	"RETAILER_SITE_CODE"	INTEGER,
	"RETAILER_CONTACT_CODE"	INTEGER,
	"SALES_STAFF_CODE"	INTEGER,
	"SALES_BRANCH_CODE"	INTEGER,
	"ORDER_DATE"	TEXT,
	"ORDER_METHOD_CODE"	INTEGER,
	PRIMARY KEY (ORDER_NUMBER),
	FOREIGN KEY (RETAILER_SITE_CODE) REFERENCES retailer_site(RETAILER_SITE_CODE),
	FOREIGN KEY (RETAILER_CONTACT_CODE) REFERENCES retailer_contact(RETAILER_CONTACT_CODE),
	FOREIGN KEY (SALES_STAFF_CODE) REFERENCES sales_staff(SALES_STAFF_CODE),
	FOREIGN KEY (SALES_BRANCH_CODE) REFERENCES sales_branch(SALES_BRANCH_CODE),
	FOREIGN KEY (ORDER_METHOD_CODE) REFERENCES order_method(ORDER_METHOD_CODE)
);

CREATE TABLE IF NOT EXISTS "order_details" (
	"ORDER_DETAIL_CODE"	INTEGER,
	"ORDER_NUMBER"	INTEGER,
	"PRODUCT_NUMBER"	INTEGER,
	"QUANTITY"	INTEGER,
	"UNIT_COST"	REAL,
	"UNIT_PRICE"	REAL,
	"UNIT_SALE_PRICE"	REAL,
	PRIMARY KEY (ORDER_DETAIL_CODE),
	FOREIGN KEY (ORDER_NUMBER) REFERENCES order_header(ORDER_NUMBER),
	FOREIGN KEY (PRODUCT_NUMBER) REFERENCES product(PRODUCT_NUMBER)
);

CREATE TABLE IF NOT EXISTS "returned_item" (
	"RETURN_CODE"	INTEGER,
	"RETURN_DATE"	TEXT,
	"ORDER_DETAIL_CODE"	INTEGER,
	"RETURN_REASON_CODE"	INTEGER,
	"RETURN_QUANTITY"	INTEGER,
	PRIMARY KEY (RETURN_CODE),
	FOREIGN KEY (ORDER_DETAIL_CODE) REFERENCES order_details(ORDER_DETAIL_CODE),
	FOREIGN KEY (RETURN_REASON_CODE) REFERENCES return_reason(RETURN_REASON_CODE)
);